### ISSUE TITLE
Make fails because Godeps/Godeps.json not checked in

### ISSUE THREAD

**Issue by untoldone** [inconshreveable/gonative#12]
e.g.

    $ make
    /Users/untoldone/Source/go/src/github.com/inconshreveable/gonative/Godeps/_workspace/bin/godep restore
    godep: open /Users/untoldone/Source/go/src/github.com/inconshreveable/gonative/Godeps/Godeps.json: no such file or directory
    make: *** [workspace] Error 1

**Comment by inconshreveable** [comment]
Added godeps, sorry about that!
