### ISSUE TITLE
golang 1.4.2 do not have freebsd release package

### ISSUE THREAD

**Issue by StudioEtrange** [inconshreveable/gonative#13]
so if we use --version='1.4.2', gonative stop because it did not found freebsd package

**Comment by inconshreveable** [comment]
Yeah, weird looks like they haven't put it up there. Maybe post on the go mailing list and ask where the freebsd builds are?

You can always use the `-platforms` switch to only build the platforms you want:

```shell
gonative -version=1.4.2 -platforms="windows_amd64 linux_amd64 darwin_amd64"
```
