### ISSUE TITLE
Go 1.5.1 support

### ISSUE THREAD

**Issue by dadgar** [inconshreveable/gonative#19]

**Comment by inconshreveable** [comment]
yep, this would be great, happy to take a PR for it. it might require code changes because of how Go's cross-compilation has changed in 1.5 but i'm not sure and haven't looked closely at that yet

**Comment by F21** [comment]
Would love to see this one happen as well!

**Comment by jchenry** [comment]
From what I have tested, the only things that needs to be done is GOROOT_BOOTSTRAP needs to be set before you run gonative. i did hit one issue with a 404 while downloading, but i believe this to be due to a dropping of a previously supported platform.

**Comment by tchap** [comment]
:+1:

**Comment by inconshreveable** [comment]
fixed by #22
